language: "en-US"
early_access: true
reviews:
  profile: "assertive"
  request_changes_workflow: true
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: true
  auto_review:
    enabled: true
    drafts: false
chat:
  auto_reply: true
knowledge_base:
  learnings:
    scope: local
  web_search:
    enabled: true