# Codecov configuration for Rust project
# Documentation: https://docs.codecov.com/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: '70...100'

  status:
    project:
      default:
        target: 85%
        threshold: 1%
        if_ci_failed: error
    patch:
      default:
        target: 80%
        threshold: 1%
        if_ci_failed: error

comment:
  layout: 'header, diff, flags, components, footer'
  behavior: default
  require_changes: false
  require_base: true
  require_head: true

  # Show coverage changes in PR comments
  show_carryforward_flags: false

github_checks:
  annotations: true

# Ignore patterns for coverage reporting
ignore:
  - 'python'
  - '**/tests/'
  - 'benches/'
  - 'examples/'
  - 'scripts/'
  - 'docs/'
  - '*.md'
  - '*.py'
  - 'Cargo.toml'
  - 'Cargo.lock'

# Flag configuration for different components
flags:
  unittests:
    paths:
      - src/
    carryforward: false
