[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
authors = ["Konstantin Vyatkin <tino@vtkn.io>"]
edition = "2024"
homepage = "https://github.com/tinovyatkin/serpen"
license = "MIT"
repository = "https://github.com/tinovyatkin/serpen"
description = "Python source bundler that produces a single .py file from multi-module projects"

[workspace.dependencies]
once_cell = "1.18"

# CLI and argument parsing
clap = { version = "4.0", features = ["derive"] }

# Python parsing
rustpython-parser = "0.4"

# Serialization and configuration
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"

# Error handling and logging
anyhow = "1.0"
env_logger = "0.11"
log = "0.4"

# Graph and data structures
indexmap = "2.0"
petgraph = "0.8"

# Utilities
regex = "1.5"
walkdir = "2.3"

# Python bindings (optional)
pyo3 = "0.25"
pyo3-build-config = "0.25"

# Testing
tempfile = "3.8"
