[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Tino Vyatkin <tino@vyatk.in>"]
license = "MIT"
repository = "https://github.com/tinovyatkin/serpen"
homepage = "https://github.com/tinovyatkin/serpen"
description = "Python source bundler that produces a single .py file from multi-module projects"

[workspace.dependencies]
once_cell = "1.18"

# CLI and argument parsing
clap = { version = "4.0", features = ["derive"] }

# Python parsing
rustpython-parser = "0.4"

# Serialization and configuration
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"

# Error handling and logging
anyhow = "1.0"
log = "0.4"
env_logger = "0.11"

# Graph and data structures
petgraph = "0.8"
indexmap = "2.0"

# Utilities
walkdir = "2.3"
regex = "1.5"

# Python bindings (optional)
pyo3 = "0.25"
pyo3-build-config = "0.25"

# Testing
tempfile = "3.8"
