#!/usr/bin/env python3
# Generated by Cribo - Python Source Bundler
# https://github.com/ophidiarium/cribo

import functools
import types

my_package = types.SimpleNamespace()
my_package.__name__ = "my_package"
my_package.__version__ = types.SimpleNamespace()


@functools.cache
def __cribo_init___cribo_ffea93_my_package___version__():
    module = types.SimpleNamespace()
    module.__name__ = "my_package.__version__"
    """Version information for my_package"""
    __version__ = "1.2.3"
    module.__version__ = __version__
    print("Loading version module...")
    return module


"""Test importing just __version__"""
print(f"Version: {__version__}")
