[build]
rustflags = ["-Ctarget-cpu=native"]

[net]
git-fetch-with-cli = true
retry = 10

# statically link the C runtime so the executable does not depend on
# that shared/dynamic library.
#
# See: https://github.com/astral-sh/ruff/issues/11503
[target.'cfg(all(target_env="msvc", target_os = "windows"))']
rustflags = ["-C", "target-feature=+crt-static"]

[alias]
dev = "run --package serpen --bin serpen"
bench-local = "bench --bench bundling"
bench-save = "bench --bench bundling -- --save-baseline main"
bench-compare = "bench --bench bundling -- --baseline main"
# Note: bench-bencher requires the bench-bencher.sh script
# Run: ./scripts/bench-bencher.sh

# Coverage commands using cargo-llvm-cov
coverage = "llvm-cov --html --open"
coverage-text = "llvm-cov --text"
coverage-lcov = "llvm-cov --lcov --output-path target/llvm-cov/lcov.info"
coverage-json = "llvm-cov --json --output-path target/llvm-cov/coverage.json"
coverage-clean = "llvm-cov clean"

# Branch coverage commands (requires nightly Rust)
coverage-branch = "llvm-cov --html --open --branch"
coverage-branch-text = "llvm-cov --text --branch"
coverage-branch-lcov = "llvm-cov --lcov --output-path target/llvm-cov/lcov-branch.info --branch"
