#!/usr/bin/env python3
# Generated by Cribo - Python Source Bundler
# https://github.com/ophidiarium/cribo

import functools
import types

my_package = types.SimpleNamespace()
my_package.__name__ = "my_package"
my_package.utils = types.SimpleNamespace()
my_package.__version__ = types.SimpleNamespace()


@functools.cache
def __cribo_init___cribo_ffea93_my_package___version__():
    module = types.SimpleNamespace()
    module.__name__ = "my_package.__version__"
    """Version information for my_package"""
    __version__ = "1.2.3"
    print("Loading version module...")
    return module


@functools.cache
def __cribo_init___cribo_0a2815_my_package_utils():
    module = types.SimpleNamespace()
    module.__name__ = "my_package.utils"
    """Utility module that imports version from another module"""
    my_package.__version__ = __cribo_init___cribo_ffea93_my_package___version__()
    __version__ = my_package.__version__.__version__
    module.__version__ = __version__
    print("Loading utils module...")

    def get_version():
        """Return the package version"""
        return __version__

    module.get_version = get_version
    return module


"""Test cross-module attribute imports like requests.__version__"""
utils = utils_my_package
print(f"Version from utils: {utils.get_version()}")
print(f"Direct __version__ access: {utils.__version__}")
