[profile.tp-test-linux.junit]
path = "junit.xml"
report-name = "Cribo tests (Linux)"
store-success-output = true
store-failure-output = true

[profile.tp-test-mac.junit]
path = "junit.xml"
report-name = "Cribo tests (Mac)"
store-success-output = true
store-failure-output = true

[profile.tp-test-win.junit]
path = "junit.xml"
report-name = "Cribo tests (Windows)"
store-success-output = true
store-failure-output = true
