name: Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  id-token: write
  contents: read
  checks: write
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Initialize ecosystem submodules
        run: |
          git submodule update --init --recursive ecosystem/

      - name: Set up Rust toolchain
        run: rustup show

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "rust-cache-${{ hashFiles('**/Cargo.lock') }}"
          cache-on-failure: true

      - name: Set up uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          activate-environment: true
          python-version: 3.12

      - name: Install Python dependencies
        run: uv sync --all-groups

      - name: 'Install cargo nextest'
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Generate coverage report
        shell: bash
        env:
          NEXTEST_PROFILE: 'ci'
          RUSTFLAGS: '-C instrument-coverage'
        run: |
          mkdir -p target/llvm-cov
          cargo llvm-cov nextest --workspace --locked --no-fail-fast --all-features --lcov --output-path target/llvm-cov/lcov-branch.info

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          files: target/nextest/ci/junit.xml
          use_oidc: true
          verbose: true

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: target/llvm-cov/lcov-branch.info
          fail_ci_if_error: false
          use_oidc: true
          verbose: true

      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: target/llvm-cov/lcov-branch.info
