name: Automated Releases
on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * *' # runs daily at midnight UTC

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # needed to create tags and releases
      pull-requests: write # needed to create/update the release PR
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run release-please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
